name: Deploy to SageMaker Endpoint

on:
  workflow_run:
    workflows: ["Train Model with SageMaker"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Build Docker image
        run: docker build -t digital-recognition-ml .
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Login to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry lock --no-update
          poetry install

      - name: Tag Docker image
        run: docker tag digital-recognition-ml:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/digital-recognition-ml:latest

      - name: Push Docker image
        run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/digital-recognition-ml:latest

      - name: Get config values
        id: get_config
        run: |
          BUCKET_NAME=$(yq e '.bucket_name' config.yml)
          OUTPUT_PATH=$(yq e '.output_path' config.yml)
          MODEL_VERSION=$(yq e '.model_version' config.yml)
          echo "BUCKET_NAME=${BUCKET_NAME}" >> $GITHUB_ENV
          echo "OUTPUT_PATH=${OUTPUT_PATH}" >> $GITHUB_ENV
          echo "MODEL_VERSION=${MODEL_VERSION}" >> $GITHUB_ENV

      - name: Verify environment variables
        run: |
          echo "BUCKET_NAME=${BUCKET_NAME}"
          echo "OUTPUT_PATH=${OUTPUT_PATH}"
          echo "MODEL_VERSION=${MODEL_VERSION}"

      - name: Deploy to SageMaker
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ECR_IMAGE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/digital-recognition-ml:latest
          MODEL_ARTIFACT: s3://${{ env.BUCKET_NAME }}/${{ env.OUTPUT_PATH }}_${{ env.MODEL_VERSION }}/model.tar.gz
          ROLE: ${{ secrets.SAGEMAKER_ROLE }}
          VERSION: ${{ env.MODEL_VERSION }}
        run: |
          poetry run python src/deploy/deploy_to_sagemaker.py
