name: Train Model with SageMaker

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry lock --no-update
          poetry install

      - name: Get config values
        id: get_config
        run: |
          BUCKET_NAME=$(yq e '.bucket_name' config.yml)
          OUTPUT_PATH=$(yq e '.output_path' config.yml)
          MODEL_VERSION=$(yq e '.model_version' config.yml)

          echo "BUCKET_NAME=${BUCKET_NAME}" >> $GITHUB_ENV
          echo "OUTPUT_PATH=${OUTPUT_PATH}" >> $GITHUB_ENV
          echo "MODEL_VERSION=${MODEL_VERSION}" >> $GITHUB_ENV

      - name: Verify environment variables
        run: |
          echo "BUCKET_NAME=${BUCKET_NAME}"
          echo "OUTPUT_PATH=${OUTPUT_PATH}"
          echo "MODEL_VERSION=${MODEL_VERSION}"

      - name: Run SageMaker training job
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SAGEMAKER_ROLE: ${{ secrets.SAGEMAKER_ROLE }}
          BUCKET_NAME: ${{ env.BUCKET_NAME }}
          OUTPUT_PATH: ${{ env.OUTPUT_PATH }}
          MODEL_VERSION: ${{ env.MODEL_VERSION }}
        run: |
          poetry run python src/train/sagemaker_train.py
